# permissions for end users to view opensearchroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchrole-viewer-role
rules:
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchroles/status
  verbs:
  - get
