# permissions for end users to edit opensearchroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchrole-editor-role
rules:
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchroles/status
  verbs:
  - get
