# permissions for end users to edit opensearchuserrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchuserrolebinding-editor-role
rules:
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchuserrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchuserrolebindings/status
  verbs:
  - get
