# permissions for end users to edit opensearchusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchuser-editor-role
rules:
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eliatra.opensearch.eliatra.io
  resources:
  - opensearchusers/status
  verbs:
  - get
