---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - ismpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - ismpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - ismpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchactiongroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchactiongroups/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchactiongroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchclusters/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchcomponenttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchcomponenttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchcomponenttemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchindextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchindextemplates/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchindextemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchroles/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchtenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchtenants/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchtenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchuserrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchuserrolebindings/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchuserrolebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchusers/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.eliatra.io
  resources:
  - opensearchusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
