# A special manual workflow to push a busybox image into our public registry. This image is used for the init helper containers
name: Push busybox image to docker hub
on: workflow_dispatch


jobs:
  release:
    name: Push busybox image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and Push docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd opensearch-operator
          export IMG=docker.io/eliatra/eoko-busybox:1.27.2-buildx
          echo $IMG
          docker buildx build -f Dockerfile-busybox --platform="linux/amd64,linux/arm,linux/arm64" . -t $IMG --push
          cd ..
