name: "Publish Release from tag"
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set Env
        id: github-ver
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Build and Push docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd opensearch-operator
          make test
          export IMG=docker.io/eliatra/opensearch-operator:$RELEASE_VERSION
          echo $IMG
          docker buildx build -t $IMG --platform="linux/amd64,linux/arm,linux/arm64" . -f Dockerfile --push

      - name: Make sure helm chart has correct versions
        run: |
          sed -i -e 's/^appVersion:.*/appVersion: '$RELEASE_VERSION'/' charts/opensearch-operator/Chart.yaml
          sed -i -e 's/^version:.*/version: '$RELEASE_VERSION'/' charts/opensearch-operator/Chart.yaml

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Publish opensearch-cluster helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.1
        with:
          name: eoko-cluster
          path: charts/opensearch-cluster
          repository: ${{ secrets.DOCKERHUB_USERNAME }}
          tag: ${{ github.ref }}
          registry: docker.io
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false

      - name: Publish opensearch-operator helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.1
        with:
          name: eoko
          path: charts/opensearch-operator
          repository: ${{ secrets.DOCKERHUB_USERNAME }}
          tag: ${{ github.ref }}
          registry: docker.io
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
